# Generated by Django 4.2.2 on 2023-06-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description_uz',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
