# Generated by Django 4.2.2 on 2023-06-07 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_category_description_uz'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='title_uz',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
