# Generated by Django 4.2.2 on 2023-06-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='new', max_length=8),
        ),
    ]
